tosca_definitions_version: cloudify_dsl_1_3

imports:
  - https://cloudify.co/spec/cloudify/6.3.0/types.yaml
  - plugin:cloudify-kubernetes-plugin?version===2.13.9

inputs:

  k8s_deployment_id:
    type: string
    default: 85cbb865-19f3-43b7-9f63-ed12b849d381
  
  kubeconfig_storager_blueprint_id:
    type: string
    default: kubeconfig_storager
  
  nfd_blueprint_id:
    type: string
    default: nfd-blueprint
  
  kube_cert_blueprint_id:
    type: string
    default: k8s_cert_configuration_new

node_templates:
  
  kubeconfig_storager:
    type: cloudify.nodes.ServiceComponent
    properties:
      resource_config:
        blueprint:
          external_resource: true
          id: { get_input: kubeconfig_storager_blueprint_id }
        deployment:
          inputs: 
            k8s_deployment_id:  { get_input: k8s_deployment_id }

  nfd_feature:
    type: cloudify.nodes.ServiceComponent
    properties:
      resource_config:
        blueprint:
          external_resource: true
          id: { get_input: nfd_blueprint_id}
        deployment:
          inputs: 
            k8s_deployment_id:  { get_input: k8s_deployment_id }

    relationships:
      - type: cloudify.relationships.depends_on
        target: kubeconfig_storager
