tosca_definitions_version: cloudify_dsl_1_4

imports:
  - https://cloudify.co/spec/cloudify/6.4.0.dev1/types.yaml
  - plugin:cloudify-kubernetes-plugin?version===2.13.9

inputs:

  k8s_deployment_id:
    type: deployment_id
    constraints:
    - labels:
      - csys-obj-type: service
      - obj-type: terraform

  submanager_name:
    type: string
    default: cloudify-manager-aio


node_templates:
  
  kubeconfig_storager:
    type: cloudify.nodes.ServiceComponent
    properties:
      resource_config:
        blueprint:
          main_file_name: 'blueprint.yaml'
          external_resource: false
          blueprint_archive: https://github.com/mateuszmizer/poc_dish/raw/main/kubeconfig_storager.zip
        deployment:
          inputs: 
            k8s_deployment_id: { get_input: k8s_deployment_id }

  nfd_feature:
    type: cloudify.nodes.ServiceComponent
    properties:
      resource_config:
        blueprint:
          main_file_name: 'main.yaml'
          external_resource: false
          blueprint_archive: https://github.com/mateuszmizer/poc_dish/raw/main/nfd-blueprint.zip
        deployment:
          inputs: 
            k8s_deployment_id: { get_input: k8s_deployment_id }
    relationships:
      - type: cloudify.relationships.depends_on
        target: kubeconfig_storager
  
  submanager:
    type: cloudify.nodes.Component
    properties:
      resource_config:
        blueprint:
          main_file_name: 'helm_manager_aio.yaml'
          external_resource: false
          blueprint_archive: https://github.com/mateuszmizer/poc_dish/raw/main/submanager_helm_aio.zip
        deployment:
          id: { get_input: submanager_name }
          inputs:
            k8s_deployment_id: { get_input: k8s_deployment_id }
    relationships:
      - type: cloudify.relationships.depends_on
        target: kubeconfig_storager

  # policy_executor:
  #   type: cloudify.nodes.Component
  #   properties:
  #     resource_config:
  #       blueprint:
  #         main_file_name: 'helm_manager_aio.yaml'
  #         external_resource: false
  #         blueprint_archive: https://github.com/mateuszmizer/poc_dish/raw/main/submanager_helm_aio.zip
  #       deployment:
  #         inputs:
  #           submanager_deployment_id: { get_attribute: [submanager, node_instance_id] } 
  #   relationships:
  #     - type: cloudify.relationships.depends_on
  #       target: submanager

capabilities:
  cloudify_manager_endpoint:
    value: { get_attribute: [ submanager, capabilities, cloudify_manager_endpoint ] }
  SUBMANAGER_ID:
    value: { get_attribute: [submanager, node_instance_id] }
  # SLA:
  #   value: { get_attribute: [ policy_matcher, capabilities, SLA_POLICY ] }
  
